### ISSUE TITLE
🚀 Feature: <support commonjs>

### ISSUE THREAD

**Issue by zhfnjust** [JoshuaKGoldberg/console-table-without-index#77]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/console-table-without-index/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

support commonjs

**Comment by JoshuaKGoldberg** [comment]
This issue has exactly two words that are not in the template: _"support commonjs"_. Can you please say more? How are you attempting to call this project's API(s)? What is the situation where you can't use ESM?
